// Regenerates src/fonts-gen.js: the latin woff2 subsets of the app's two display
// fonts, embedded as data: URIs so the app makes zero runtime network requests.
// Run: node tools/fetch-fonts.js   (needs network; the generated file is committed)
const https = require("https");
const fs = require("fs");

const CSS_URL = "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=IBM+Plex+Mono:wght@500&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const get = (url, binary) => new Promise((resolve, reject) => {
  https.get(url, { headers: { "User-Agent": UA } }, (res) => {
    const chunks = [];
    res.on("data", (c) => chunks.push(c));
    res.on("end", () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
  }).on("error", reject);
});

(async () => {
  const css = await get(CSS_URL, false);
  // Parse @font-face blocks; keep only the latin subset of each family/weight.
  const faces = [];
  const re = /\/\* ([a-z-]+) \*\/\s*@font-face\s*{([^}]+)}/g;
  let m;
  while ((m = re.exec(css))) {
    if (m[1] !== "latin") continue;
    const body = m[2];
    const fam = (body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const wght = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (fam && wght && url) faces.push({ fam, wght, url });
  }
  if (faces.length < 3) throw new Error(`expected 3 latin faces, got ${faces.length}`);
  let out = "// GENERATED by tools/fetch-fonts.js — latin woff2 subsets as data: URIs.\n// Kills the runtime Google Fonts request: offline-true, no third-party disclosure.\nexport const FONT_CSS = `";
  for (const f of faces) {
    const buf = await get(f.url, true);
    console.log(`${f.fam} ${f.wght}: ${(buf.length / 1024).toFixed(1)}KB`);
    out += `@font-face{font-family:'${f.fam}';font-style:normal;font-weight:${f.wght};font-display:swap;src:url(data:font/woff2;base64,${buf.toString("base64")}) format('woff2');unicode-range:U+0000-00FF,U+2013-2014,U+2018-201A,U+201C-201E,U+2022,U+2026,U+2192,U+2660-2666;}\n`;
  }
  out += "`;\n";
  fs.writeFileSync("src/fonts-gen.js", out);
  console.log(`src/fonts-gen.js written (${(out.length / 1024).toFixed(0)}KB)`);
})();
